# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# C:\Users\WIN8\workspace\WINX64\Blender\conda\Blender, last modified Fri Jun 19 10:42:10 2020
# ------------------------------------------------

package:
    name: python-blender
    version: '2.83'
source:
    -   folder: blender_extras/release/scripts/addons
        git_rev: v2.83
        git_url: git://git.blender.org/blender-addons.git
    -   folder: blender_extras/release/scripts/addons_contrib
        git_rev: v2.83
        git_url: git://git.blender.org/blender-addons-contrib.git
    -   folder: blender_extras/release/datafiles/locale
        git_rev: v2.83
        git_url: git://git.blender.org/blender-translations.git
    -   folder: blender_extras/source/tools
        git_rev: v2.83
        git_url: git://git.blender.org/blender-dev-tools.git
    -   folder: blender
        git_rev: v2.83
        git_url: git://git.blender.org/blender.git
        patches:
            - platform.patch
build:
    missing_dso_whitelist:
        - C:\Windows\System32\AVIFIL32.dll
        - C:\Windows\System32\MSVCP140.dll
        - C:\Windows\System32\OPENGL32.dll
        - C:\Windows\System32\SHFOLDER.dll
        - C:\Windows\System32\SHLWAPI.dll
        - C:\Windows\System32\VCRUNTIME140.dll
        - C:\Windows\System32\VCRUNTIME140_1.dll
    number: '0'
    string: '1592498919'
requirements:
    build:
        - bullet 2.83 1588359114
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py38_0
        - cmake 3.17.2 h33f27b4_0
        - git 2.23.0 h6bb4b03_0
        - jpeg 9b hb83a4c4_2
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-patch 2.7.5 2
        - msys2-conda-epoch 20160418 1
        - openssl 1.1.1g he774522_0
        - pip 20.1.1 py38_1
        - python 3.8.3 he1778fa_0
        - setuptools 47.3.0 py38_0
        - sqlite 3.32.2 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
        - wheel 0.34.2 py38_0
        - wincertstore 0.2 py38_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - jpeg >=9b,<10a
        - python >=3.8,<3.9.0a0
        - zlib >=1.2.11,<1.3.0a0
about:
    home: https://www.blender.org/
    license: GPL
extra:
    copy_test_source_files: true
    final: true
