# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-mpc, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-mpc
    version: 1.0.3
source:
    md5: 5c24d319656ed61e517dfa0fee7e475c
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-mpc-1.0.3-2.src.tar.gz
build:
    number: '3'
    string: '3'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2w64-mpfr
about:
    home: http://www.multiprecision.org
    license: LGPL
    summary: Multiple precision complex arithmetic library (mingw-w64)
extra:
    msys2-binaries:
        win-32:
            md5: 719e76fa7a54a8676d2e60af3bb13c45
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-mpc
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-mpc-1.0.3-2-any.pkg.tar.xz
        win-64:
            md5: df1a7d4050568d83c265ae78c32ef30b
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-mpc
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-mpc-1.0.3-2-any.pkg.tar.xz
