# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-binutils, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-binutils
    version: 2.25.1
source:
    md5: 37de305aa7a535319b5072a8070e1704
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-binutils-2.25.1-4.src.tar.gz
build:
    number: '5'
    string: '5'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2w64-libiconv
        - m2w64-zlib
about:
    home: http://www.gnu.org/software/binutils/
    license: GPL
    summary: A set of programs to assemble and manipulate binary and object files
        (mingw-w64)
extra:
    msys2-binaries:
        win-32:
            md5: fec623de1f1a075da9c731b9061c2b34
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-binutils
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-binutils-2.25.1-4-any.pkg.tar.xz
        win-64:
            md5: 49f6fa8690e4e81f8c775b71d67adaed
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-binutils
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-binutils-2.25.1-4-any.pkg.tar.xz
