# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-headers-git, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-headers-git
    version: 5.0.0.4636.c0ad18a
source:
    md5: 60930c7e44a1dc9220d32e96ee7f2941
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-headers-git-5.0.0.4636.c0ad18a-1.src.tar.gz
build:
    number: '2'
    string: '2'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
about:
    home: http://mingw-w64.sourceforge.net
    license: custom
    summary: MinGW-w64 headers for Windows
extra:
    msys2-binaries:
        win-32:
            md5: 9781c1cab828dfffd7cbb8621cd5e445
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-headers-git
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-headers-git-5.0.0.4636.71f47f6-1-any.pkg.tar.xz
        win-64:
            md5: be251a450a8317837ed32a1e7b801192
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-headers-git
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-headers-git-5.0.0.4636.c0ad18a-1-any.pkg.tar.xz
