# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-gcc, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-gcc
    version: 5.3.0
source:
    md5: 4698350ad11d86459ffc4843fe1c951f
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-gcc-5.3.0-5.src.tar.gz
build:
    number: '6'
    string: '6'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2w64-binutils
        - m2w64-crt-git
        - m2w64-headers-git
        - m2w64-isl
        - m2w64-libiconv
        - m2w64-mpc
        - m2w64-gcc-libs
        - m2w64-windows-default-manifest
        - m2w64-winpthreads-git
        - m2w64-zlib
about:
    home: https://gcc.gnu.org
    license: GPL, LGPL, FDL, custom
    summary: GNU Compiler Collection (C,C++,OpenMP) for MinGW-w64
extra:
    msys2-binaries:
        win-32:
            md5: 41d764b19ff41af2ffcd005ff1cf38b7
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-gcc
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-gcc-5.3.0-5-any.pkg.tar.xz
        win-64:
            md5: 02fcc676cd51472a9bc4fe17d2d138eb
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-gcc
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-gcc-5.3.0-5-any.pkg.tar.xz
