# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Wed Jul 15 18:28:32 2020
# ------------------------------------------------

package:
    name: pivy
    version: 0.6.6.a0
source:
    fn: pivy.tar.gz
    patches:
        - install.patch
    sha256: f9ea3cf9549d71c68cbc0f2df6c23616c2f1a9132151545db5506c0bd7348c9a
    url: https://github.com/FreeCAD/pivy/archive/0.6.6.a0.tar.gz
build:
    number: '0'
    string: py38h026d3d0_0
requirements:
    build:
        - cmake 3.17.0 he025d50_0
        - msinttypes r26 2
        - ninja 1.10.0 h1ad3211_0
        - swig 4.0.2 0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - boost-cpp 1.72.0 h89d28cc_2
        - bzip2 1.0.8 hfa6e2cd_2
        - ca-certificates 2020.6.20 hecda079_0
        - coin3d 4.0.0 h93788fa_1009
        - expat 2.2.9 he025d50_2
        - icu 64.2 he025d50_1
        - jpeg 9d he774522_0
        - libclang 9.0.1 default_hf44288c_0
        - libpng 1.6.37 hfe6a214_1
        - lz4-c 1.9.2 h62dcd97_1
        - openssl 1.1.1g he774522_0
        - python 3.8.2 h5fd99cc_7_cpython
        - python_abi 3.8 1_cp38
        - qt 5.12.5 h7ef1ec2_0
        - soqt 1.6.0 h95c7cbc_1
        - sqlite 3.32.3 he774522_1
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - xz 5.2.5 h62dcd97_1
        - zlib 1.2.11 h2fa13f4_1006
        - zstd 1.4.4 h9f78265_3
    run:
        - coin3d
        - pyside2
        - python >=3.8,<3.9.0a0
        - python_abi 3.8.* *_cp38
        - qt >=5.12.5,<5.13.0a0
        - qt >=5.12.5,<5.13.0a0
        - soqt
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    imports:
        - pivy.coin
        - pivy.gui.soqt
about:
    dev_url: https://github.com/FreeCAD/pivy
    doc_url: https://github.com/FreeCAD/pivy
    home: https://github.com/FreeCAD/pivy
    license: ISC
    license_file: LICENSE
    summary: python bindings to coin3d.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - looooo
