# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Feb 21 13:47:41 2020
# ------------------------------------------------

package:
    name: pcl
    version: 1.9.1
source:
    fn: pcl-1.9.1.tar.gz
    patches:
        - boost1.70.patch
        - except.patch
    sha256: 0add34d53cd27f8c468a59b8e931a636ad3174b60581c0387abb98a9fc9cddb6
    url: https://github.com/pointcloudlibrary/pcl/archive/pcl-1.9.1.tar.gz
build:
    number: '1005'
    string: h674dfd5_1005
requirements:
    build:
        - cmake 3.16.4 he025d50_0
        - ninja 1.10.0 h1ad3211_0
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - vs2015_win-64 14.0.25420 h55c1224_11
    host:
        - boost-cpp 1.72.0 h0caebb8_0
        - bzip2 1.0.8 hfa6e2cd_2
        - eigen 3.3.7 he980bc4_1001
        - flann 1.9.1 h69e8c9e_1006
        - hdf5 1.10.5 nompi_ha405e13_1104
        - qhull 2015.2 he980bc4_1000
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - zlib 1.2.11 h2fa13f4_1006
    run:
        - boost-cpp >=1.72.0,<1.72.1.0a0
        - flann >=1.9.1,<1.9.2.0a0
        - qhull
        - vc >=14.1,<15.0a0
test:
    commands:
        - if not exist %LIBRARY_INC%\\pcl-1.9\\pcl exit 1
about:
    description: 'The Point Cloud Library (PCL) is a standalone, large scale, open
        project for 2D/3D image and point cloud processing.

        '
    dev_url: https://github.com/pointcloudlibrary/pcl
    doc_url: http://www.pointclouds.org
    home: http://www.pointclouds.org
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Point Cloud Library (PCL)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chambbj
        - hobu
