# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-zlib, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-zlib
    version: 1.2.8
source:
    md5: 32078e2a67e34ff6c0b1795fe6ed9d36
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-zlib-1.2.8-9.src.tar.gz
build:
    number: '10'
    string: '10'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2w64-bzip2
about:
    home: http://www.zlib.net/
    license: ZLIB
    summary: Compression library implementing the deflate compression method found
        in gzip and PKZIP (mingw-w64)
extra:
    msys2-binaries:
        win-32:
            md5: 87c65e9b2930436a75dfd7d459ae98cb
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-zlib
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-zlib-1.2.8-9-any.pkg.tar.xz
        win-64:
            md5: 60c3a388478f411b7a0908441ebeb537
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-zlib
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-zlib-1.2.8-9-any.pkg.tar.xz
