# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-isl, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-isl
    version: 0.16.1
source:
    md5: 655455624147d73944a897b082d11d58
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-isl-0.16.1-1.src.tar.gz
build:
    number: '2'
    string: '2'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
about:
    home: http://isl.gforge.inria.fr/
    license: MIT
    summary: Library for manipulating sets and relations of integer points bounded
        by linear constraints (mingw-w64)
extra:
    msys2-binaries:
        win-32:
            md5: 9a8fb0947d5ffb7e88686a1cdb3d4ff3
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-isl
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-isl-0.16.1-1-any.pkg.tar.xz
        win-64:
            md5: 8907528ac4565caa1a4ebbae45147f0f
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-isl
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-isl-0.16.1-1-any.pkg.tar.xz
