# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Sat Jun 20 21:36:16 2020
# ------------------------------------------------

package:
    name: certifi
    version: 2020.6.20
source:
    -   folder: certifi
        sha256: 5930595817496dd21bb8dc35dad090f1c2cd0adfaf21204bf6732ca5d8ee34d3
        url: https://pypi.io/packages/source/c/certifi/certifi-2020.6.20.tar.gz
    -   folder: pip_wheel
        sha256: 993134f0475471b91452ca029d4390dc8f298ac63a712814f101cd1b6db46676
        url: https://pypi.io/packages/py2.py3/p/pip/pip-19.1.1-py2.py3-none-any.whl
    -   folder: setuptools_wheel
        sha256: c7769ce668c7a333d84e17fe8b524b1c45e7ee9f7908ad0a73e1eda7e6a5aebf
        url: https://pypi.io/packages/py2.py3/s/setuptools/setuptools-41.0.1-py2.py3-none-any.whl
build:
    number: '0'
    string: py38h32f6830_0
requirements:
    host:
        - ca-certificates 2020.6.20 hecda079_0
        - openssl 1.1.1g he774522_0
        - python 3.8.2 h5fd99cc_7_cpython
        - python_abi 3.8 1_cp38
        - sqlite 3.30.1 hfa6e2cd_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
    run:
        - python >=3.8,<3.9.0a0
        - python_abi 3.8.* *_cp38
test:
    imports:
        - certifi
about:
    description: 'Certifi is a curated collection of Root Certificates for validating
        the

        trustworthiness of SSL certificates while verifying the identity of TLS

        hosts.

        '
    dev_url: https://github.com/certifi/python-certifi
    doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/certifi
    home: http://certifi.io/
    license: ISC
    license_file: certifi/LICENSE
    summary: Python package for providing Mozilla's CA Bundle.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - ocefpaf
        - pelson
        - sigmavirus24
