# This file created by conda-build 3.1.3
# meta.yaml template originally from:
# C:\ci\containers\00001dd1h3a\tmp\build\80754af9\rsync-recipes\swig-3.0.12-c_compilervs2015cxx_compilervs2015-on-nwani-win-64, last modified Wed Dec 13 08:34:40 2017
# ------------------------------------------------

package:
    name: swig
    version: 3.0.12
source:
    fn: swigwin-3.0.12.zip
    sha256: 21ce6cbe297a56b697ef6e7e92a83e75ca41dedc87e48282ab444591986c35f5
    url: http://prdownloads.sourceforge.net/swig/swigwin-3.0.12.zip
build:
    number: '3'
    string: h047fa9f_3
requirements:
    build:
        - vs2015_win-64 14.0.25123 hf5d5b87_2
    run:
        - vc 14.*
test:
    commands:
        - swig -help
about:
    description: 'SWIG is an interface compiler that connects programs written in
        C and C++

        with scripting languages such as Perl, Python, Ruby, and Tcl. It works by

        taking the declarations found in C/C++ header files and using them to

        generate the wrapper code that scripting languages need to access the

        underlying C/C++ code. In addition, SWIG provides a variety of

        customization features that let you tailor the wrapping process to suit

        your application.

        '
    dev_url: https://github.com/swig/swig
    doc_url: http://www.swig.org/Doc3.0/index.html
    home: http://www.swig.org/
    license: GPL 3
    license_family: GPL
    license_file: LICENSE
    summary: C/C++ parser code generator
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jschueller
        - mingwandroid
        - msarahan
        - ocefpaf
