# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-windows-default-manifest, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-windows-default-manifest
    version: '6.4'
source:
    md5: 673014d2903952d1d689629d50862a97
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-windows-default-manifest-6.4-2.src.tar.gz
build:
    number: '3'
    string: '3'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
about:
    home: http://cygwin.com/
    license: BSD
    summary: Default Windows application manifest (mingw-w64)
extra:
    msys2-binaries:
        win-32:
            md5: 557bac3628b7733fc1aee6380aa03898
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-windows-default-manifest
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-windows-default-manifest-6.4-2-any.pkg.tar.xz
        win-64:
            md5: 7d0ae624c7ccc7e8dff65310b26ef2c7
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-windows-default-manifest
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-windows-default-manifest-6.4-2-any.pkg.tar.xz
