# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-bzip2, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-bzip2
    version: 1.0.6
source:
    md5: 25e32cdf485302675b293206dc554e47
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-bzip2-1.0.6-5.src.tar.gz
build:
    number: '6'
    string: '6'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2w64-gcc-libs
about:
    home: http://www.bzip.org
    license: custom
    summary: A high-quality data compression program (mingw-w64)
extra:
    msys2-binaries:
        win-32:
            md5: 723ee2f4f18735ca343f1f7daf8d8aa8
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-bzip2
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-bzip2-1.0.6-5-any.pkg.tar.xz
        win-64:
            md5: eef826afedfa502c99243cdf0783f1c3
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-bzip2
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-bzip2-1.0.6-5-any.pkg.tar.xz
