# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Apr 24 06:05:30 2020
# ------------------------------------------------

package:
    name: soqt
    version: 1.6.0
source:
    -   patches:
            - 0001-make-cpack-optional-and-disabled-by-default.patch
        sha256: 9f535af59f07c907022815679681bd345c9dec2f408c74833f6b1b24bca40e1f
        url: https://github.com/coin3d/soqt/releases/download/SoQt-1.6.0/soqt-1.6.0-src.tar.gz
build:
    number: '1'
    string: h95c7cbc_1
requirements:
    build:
        - cmake 3.17.0 he025d50_0
        - ninja 1.10.0 h1ad3211_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - boost-cpp 1.72.0 h0caebb8_0
        - bzip2 1.0.8 hfa6e2cd_2
        - ca-certificates 2020.4.5.1 hecc5488_0
        - coin3d 4.0.0 h93788fa_1009
        - expat 2.2.9 he025d50_2
        - icu 64.2 he025d50_1
        - jpeg 9c hfa6e2cd_1001
        - libclang 9.0.1 default_hf44288c_0
        - libpng 1.6.37 hfe6a214_1
        - openssl 1.1.1g he774522_0
        - qt 5.12.5 h7ef1ec2_0
        - sqlite 3.30.1 hfa6e2cd_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - zlib 1.2.11 h2fa13f4_1006
    run:
        - coin3d
        - qt >=5.12.5,<5.13.0a0
        - qt >=5.12.5,<5.13.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    commands:
        - cmake .
    files:
        - CMakeLists.txt
    requires:
        - cmake
about:
    description: SoQt is a Qt GUI component toolkit library for Coin.  It is also
        compatible with SGI and TGS Open Inventor, and the API is based on the API
        of the InventorXt GUI component toolkit.
    dev_url: https://bitbucket.org/Coin3D/soqt
    doc_url: https://bitbucket.org/Coin3D/soqt
    home: https://bitbucket.org/Coin3D/soqt
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING
    summary: SoQt library needed by Coin3d.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - looooo
