# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Thu Jul  2 18:53:08 2020
# ------------------------------------------------

package:
    name: python-language-server
    version: 0.34.1
source:
    sha256: b96ff466b5aa24e212493de863899298f229a9e250e7353972563c7f2495d23d
    url: https://pypi.org/packages/source/p/python-language-server/python-language-server-0.34.1.tar.gz
build:
    entry_points:
        - pyls = pyls.__main__:main
    number: '0'
    script: D:\\bld\\python-language-server_1593716173125\\_h_env\\python.exe -m pip
        install . --no-deps -vv
    string: py38h32f6830_0
requirements:
    host:
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h32f6830_0
        - openssl 1.1.1g he774522_0
        - pip 20.1.1 py_1
        - python 3.8.2 h5fd99cc_7_cpython
        - python_abi 3.8 1_cp38
        - setuptools 47.3.1 py38h32f6830_0
        - sqlite 3.32.3 he774522_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - wheel 0.34.2 py_1
        - wincertstore 0.2 py38_1003
    run:
        - autopep8
        - flake8 >=3.8.0
        - jedi >=0.17.0,<0.18.0a0
        - mccabe >=0.6.0,<0.7.0
        - pluggy
        - pycodestyle >=2.6.0,<2.7.0
        - pydocstyle >=2.0.0
        - pyflakes >=2.2.0,<2.3.0
        - pylint
        - python >=3.8,<3.9.0a0
        - python-jsonrpc-server >=0.3.2
        - python_abi 3.8.* *_cp38
        - rope >=0.10.5
        - setuptools
        - ujson <=1.35
        - yapf
test:
    commands:
        - python -m pip check
        - pyls --help
    requires:
        - pip
about:
    description: 'A Python 2.7 and 3.4+ implementation of the Language Server Protocol

        making use of Jedi, pycodestyle, Pyflakes and YAPF.

        '
    dev_url: https://github.com/palantir/python-language-server
    home: https://github.com/palantir/python-language-server
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: An implementation of the Language Server Protocol for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - andfoy
        - ccordoba12
        - goanpeca
        - mariusvniekerk
        - rlaverde
