# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-libiconv, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-libiconv
    version: '1.14'
source:
    md5: a342b18b24fa1e9fe379620c6e668424
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-libiconv-1.14-5.src.tar.gz
build:
    number: '6'
    string: '6'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
about:
    home: http://www.gnu.org/software/libiconv/
    license: LGPL2, documentation:GPL3
    summary: Character encoding conversion library (mingw-w64)
extra:
    msys2-binaries:
        win-32:
            md5: 2c99a163689ba8257627bb07274b3f86
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-libiconv
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-libiconv-1.14-5-any.pkg.tar.xz
        win-64:
            md5: 37418c6be92ef20be17cdc9fe844af35
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-libiconv
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-libiconv-1.14-5-any.pkg.tar.xz
