# This file created by conda-build 3.18.11
# ------------------------------------------------

package:
    name: libclang
    version: 9.0.1
source:
    -   folder: .
        patches:
            - patches/0001-Find-conda-gcc-installation.patch
            - patches/0001-Set-VERSION-in-osx-as-well.patch
            - patches/0002-Fix-sysroot-detection-for-linux.patch
            - patches/0002-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch
            - patches/0003-clang-Fix-normalizeProgramName-s-handling-of-dots-ou.patch
            - patches/amd-roc-2.7.0.diff
        sha256: 5778512b2e065c204010f88777d44b95250671103e434f9dc7363ab2e3804253
        url: https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/clang-9.0.1.src.tar.xz
    -   folder: tools/extra
        sha256: b26fd72a78bd7db998a26270ec9ec6a01346651d88fa87b4b323e13049fb6f07
        url: https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/clang-tools-extra-9.0.1.src.tar.xz
build:
    number: 0
    string: default_hf44288c_0
requirements:
    build:
        - cmake 3.16.1 he025d50_0
        - ninja 1.9.0 h1ad3211_1
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - vs2017_win-64 19.15.26726 hb4ce483_4
    host:
        - clang 9.0.1 default_hf44288c_0
        - libllvm9 9.0.1 h21ff451_0
        - llvm 9.0.1 h21ff451_0
        - llvm-tools 9.0.1 h21ff451_0
        - llvmdev 9.0.1 h21ff451_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
    run:
        - vc >=14.1,<15.0a0
test:
    commands:
        - if not exist %LIBRARY_BIN%\\libclang.dll exit 1
about:
    home: http://llvm.org/
    license: NCSA
    license_file: LICENSE.TXT
    summary: Development headers and libraries for Clang
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - inducer
        - isuruf
        - jakirkham
        - mattwala
