# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-winpthreads-git, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-winpthreads-git
    version: 5.0.0.4634.697f757
source:
    md5: 825ccecaafbc35ef5883236fe2394718
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-winpthreads-git-5.0.0.4634.697f757-1.src.tar.gz
build:
    number: '2'
    string: '2'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2w64-crt-git
        - m2w64-libwinpthread-git
about:
    home: http://mingw-w64.sourceforge.net
    license: MIT, BSD
    summary: MinGW-w64 winpthreads library
extra:
    msys2-binaries:
        win-32:
            md5: 1b104d5803b282cb0e2ee174f691a248
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-winpthreads-git
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-winpthreads-git-5.0.0.4634.1a9aeb9-1-any.pkg.tar.xz
        win-64:
            md5: 1316eff18cf721457c31412be36057cd
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-winpthreads-git
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-winpthreads-git-5.0.0.4634.697f757-1-any.pkg.tar.xz
