# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-crt-git, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-crt-git
    version: 5.0.0.4636.2595836
source:
    md5: 01ff22ae7af5c2e3d8839fd44c6380b0
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-crt-git-5.0.0.4636.2595836-1.src.tar.gz
build:
    number: '2'
    string: '2'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2w64-headers-git
about:
    home: http://mingw-w64.sourceforge.net
    license: custom
    summary: MinGW-w64 CRT for Windows
extra:
    msys2-binaries:
        win-32:
            md5: 4377ceff6d25f02b68532dafd7e41b47
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-crt-git
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-crt-git-5.0.0.4636.f97302f-1-any.pkg.tar.xz
        win-64:
            md5: aa19d9a1d9249331bf215674d1e2042f
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-crt-git
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-crt-git-5.0.0.4636.2595836-1-any.pkg.tar.xz
