# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Jan 17 17:42:05 2020
# ------------------------------------------------

package:
    name: pyside2
    version: 5.13.2
source:
    fn: pyside-setup-everywhere-src-5.13.2.tar.xz
    patches:
        - 0001-Make-pyside2-uic-executable-by-windows-shell.patch
        - 0002-Fix-Python-3.8-problems.patch
        - 0003-Optimize-the-Python-3.8-refcount-fix-a-tiny-bit.patch
        - 0004-make-compilation-work-after-backporting.patch
        - pyi.patch
    sha256: 3e255d64df08880d0281ebe86009d5ea45f24332b308954d967c33995f75e543
    url: https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.13.2-src/pyside-setup-opensource-src-5.13.2.tar.xz
build:
    detect_binary_files_with_prefix: true
    number: '2'
    string: py38hfa7ce6d_2
requirements:
    build:
        - clang 9.0.1 default_hf44288c_0
        - clang-tools 9.0.1 default_hf44288c_0
        - clangdev 9.0.1 default_hf44288c_0
        - clangxx 9.0.1 default_hf44288c_0
        - cmake 3.16.2 he025d50_1
        - libclang 9.0.1 default_hf44288c_0
        - libllvm9 9.0.1 h21ff451_0
        - llvm-tools 9.0.1 h21ff451_0
        - llvmdev 9.0.1 h21ff451_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - vs2015_win-64 14.0.25420 h55c1224_11
    host:
        - ca-certificates 2019.11.28 hecc5488_0
        - icu 64.2 he025d50_1
        - jpeg 9c hfa6e2cd_1001
        - libclang 9.0.1 default_hf44288c_0
        - libiconv 1.15 hfa6e2cd_1005
        - libpng 1.6.37 h7602738_0
        - libxml2 2.9.10 h9ce36c8_0
        - libxslt 1.1.33 heafd4d3_0
        - openssl 1.1.1d hfa6e2cd_0
        - python 3.8.1 he1f5543_1
        - qt 5.12.5 h7ef1ec2_0
        - sqlite 3.30.1 hfa6e2cd_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - zlib 1.2.11 h2fa13f4_1006
    run:
        - libxml2 >=2.9.10,<2.10.0a0
        - libxslt >=1.1.33,<2.0a0
        - python >=3.8,<3.9.0a0
        - qt >=5.12.5,<5.13.0a0
        - vc >=14.1,<15.0a0
test:
    commands:
        - shiboken2 --help
        - pyside2-lupdate -help
        - pyside2-rcc -help
        - pyside2-uic -help
    imports:
        - PySide2.Qt3DAnimation
        - PySide2.Qt3DCore
        - PySide2.Qt3DExtras
        - PySide2.Qt3DInput
        - PySide2.Qt3DLogic
        - PySide2.Qt3DRender
        - PySide2.QtCharts
        - PySide2.QtConcurrent
        - PySide2.QtCore
        - PySide2.QtDataVisualization
        - PySide2.QtGui
        - PySide2.QtHelp
        - PySide2.QtLocation
        - PySide2.QtMultimedia
        - PySide2.QtMultimediaWidgets
        - PySide2.QtNetwork
        - PySide2.QtOpenGL
        - PySide2.QtPositioning
        - PySide2.QtPrintSupport
        - PySide2.QtQml
        - PySide2.QtQuick
        - PySide2.QtQuickWidgets
        - PySide2.QtRemoteObjects
        - PySide2.QtScript
        - PySide2.QtScriptTools
        - PySide2.QtScxml
        - PySide2.QtSensors
        - PySide2.QtSql
        - PySide2.QtSvg
        - PySide2.QtTest
        - PySide2.QtTextToSpeech
        - PySide2.QtUiTools
        - PySide2.QtWebChannel
        - PySide2.QtWebEngineCore
        - PySide2.QtWebEngineWidgets
        - PySide2.QtWebSockets
        - PySide2.QtWidgets
        - PySide2.QtXml
        - PySide2.QtXmlPatterns
about:
    home: https://wiki.qt.io/PySide2
    license: LGPL3
    license_file: LICENSE.LGPLv3
    summary: Python bindings for Qt
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jschueller
