# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-gcc-fortran, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-gcc-fortran
    version: 5.3.0
source:
    md5: 4698350ad11d86459ffc4843fe1c951f
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-gcc-fortran-5.3.0-5.src.tar.gz
build:
    number: '6'
    string: '6'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2w64-gcc
        - m2w64-gcc-libgfortran
about:
    home: https://gcc.gnu.org
    license: GPL, LGPL, FDL, custom
    summary: GNU Compiler Collection (Fortran) for MinGW-w64
extra:
    msys2-binaries:
        win-32:
            md5: 15fce9686e3269eedf680ef060cb1b7f
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-gcc-fortran
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-gcc-fortran-5.3.0-5-any.pkg.tar.xz
        win-64:
            md5: 52675bd7b921463e51c443a6c2b3e45c
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-gcc-fortran
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-gcc-fortran-5.3.0-5-any.pkg.tar.xz
